### ISSUE TITLE
Silex2

### ISSUE THREAD

**Issue by rafaelnery** [propelorm/PropelServiceProvider#14]
With my fork the project, I created integration with Silex 2 and I wonder sending the pull request, which branch I use?

**Comment by cristianoc72** [comment]
Well, if you provide integration with Propel 1 then use 1.x branch, if it's
about Propel 2 so use 2.x branch.

Thanks for your work!
Il 02/gen/2016 01:09, "Rafael Nery" notifications@github.com ha scritto:

**Comment by rafaelnery** [comment]
I Send a Pull request #15 
Tks for help.
