### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by dominikzogg** [propelorm/PropelServiceProvider#4]
Hello

I would wish, that the following is in the documentation for propel noobs like me.
I only get the silex (sf2) autoloader only running if i add namespace="model" to the database schema.

<database name="silextest" namespace="model" defaultIdMethod="native">

**Comment by cristianoc72** [comment]
Hi,

you're right and (imho) it's a real bug, not just a matter of documentation improvement !
We'll work on it as soon as possible. For now, you can use a namespace different from 'model' by registering it directly into Silex autoload, or by switching on Propel internal autoload.

Best regards

**Comment by willdurand** [comment]
Fixed

**Comment by dominikzogg** [comment]
cool thx
