### ISSUE TITLE
Autoloader service removed from Silex core

### ISSUE THREAD

**Issue by cristianoc72** [propelorm/PropelServiceProvider#7]
Symfony ClassLoader component was removed from Silex core (http://silex.sensiolabs.org/doc/changelog.html), in favor of Composer autoloader, so `autoloader` service is no more provided.

We should update PropelServiceProvider:
1.     Remove the references to `$app['autoloader']`.
2.     Update the documentation: setting correctly the model namespace now is user's responsability, because the only way is via `Composer.json` (may be, it's easier to always use Propel internal autoload).
3.     `propel.model_path` parameter now it's useful only if `propel.internal_autoload` parameter is set to true.
4.     `propel.path` parameter now it's useful only if Propel isn't installed via Composer.

**Comment by willdurand** [comment]
Fixed.
